import Head from "next/head";
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import Link from "next/link";

export async function getStaticProps({ params }) {
  const page = params.page;
  return {
    props: {
      page,
    },
  };
}

export async function getStaticPaths() {
  const routes = [
    { params: { page: "1" } },
    { params: { page: "2" } },
    { params: { page: "3" } },
  ];
  return {
    paths: routes,
    fallback: false,
  };
}

export default function Page(props) {
  console.log(props);
  const page = props.page;

  return (
    <motion.div
      className={"h-screen w-full m-0 p-0"}
      initial={{ backgroundColor: "#fff" }}
      animate={{ backgroundColor: "#a1b7c4" }}
      exit={{
        backgroundColor: "#fff",
        transition: { duration: 0.3, delay: 0.4 },
      }}
      transition={{ duration: 0.3 }}
    >
      <Head>
        <title>{page}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.15 }}
        className={"container text-center py-12"}
      >
        <motion.div
          initial={{ x: -100, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ delay: 0.15 }}
        >
          <Link href={"/"}>
            <a
              className={
                "text-white uppercase tracking-widest text-sm hover:underline font-semibold"
              }
            >
              ← Go back
            </a>
          </Link>
        </motion.div>
        <h1 className={"text-4xl font-serif "}>
          A special mountain no. {page}
        </h1>
      </motion.div>
      <div className={"m-6 flex"}>
        <motion.div
          transition={{ duration: 0.4 }}
          layoutId={`mainimage${page}`}
          className={"w-full relative"}
          // style={{ paddingTop: "25%" }}
          initial={{ paddingTop: "50%" }}
          animate={{ paddingTop: "30%" }}
          exit={{ y: -50, transition: { duration: 0.2, delay: 0.3 } }}
        >
          <img
            className={"h-full w-full object-cover absolute top-0 left-0"}
            src={`/mountain${page}.jpeg`}
          />
        </motion.div>
      </div>
    </motion.div>
  );
}
