import Head from "next/head";
import { AnimatePresence, motion } from "framer-motion";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const router = useRouter();
  const { page } = router.query;
  useEffect(() => {
    if (document) console.log(document.referrer);
  }, []);
  return (
    <div>
      <Head>
        <title>Page Animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div
        className={"container text-center my-12"}
        initial={{ opacity: 0, y: 10 }}
        animate={{
          opacity: 1,
          y: 0,
          transition: { duration: 0.25, delay: 0.5 },
        }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.25 }}
      >
        <h1 className={"text-4xl font-serif "}>Welcome to nature</h1>
      </motion.div>

      <div className={"m-12 flex gap-12"}>
        {[...Array(3)].map((x, i) => (
          <Link key={i} href={`/${i + 1}`}>
            <motion.div
              // variants={variants}
              whileHover={{ scale: 1.05 }}
              transition={{ duration: 0.2 }}
              initial={{ opacity: 1 }}
              animate={{ opacity: 1 }}
              exit={
                (i + 1).toString() === page ? { opacity: 1 } : { opacity: 0 }
              }
              // animate={"enter"}
              // exit={"exit"}
              // initial={{ opacity: 0, y: 15 }}
              // animate={{ opacity: 1, y: 0 }}
              // exit={{ opacity: 0, y: 15 }}
              // transition={{ duration: 1 }}
              layoutId={`mainimage${i + 1}`}
              className={"cursor-pointer w-1/3 relative"}
            >
              <img
                className={"h-full w-full object-cover"}
                src={`/mountain${i + 1}.jpeg`}
              />
            </motion.div>
          </Link>
        ))}
      </div>
    </div>
  );
}
